# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(default='male', max_length=10),
            preserve_default=False,
        ),
    ]
